/** Educational literacy steps — never wallets, keys, balances, or seed inputs. */
export const LITERACY_STEPS = [
  {
    id: 'password-manager',
    order: 1,
    free: true,
    title: 'Use a password manager for accounts',
    summary: 'Protect exchange logins and email — not seed phrases.',
    why: 'Breached or reused passwords are a common way people lose access to exchange accounts before they ever exit to self-custody. A password manager helps you use unique, strong credentials for every account. This step is about account hygiene. It is not about storing seed phrases in a password manager.',
  },
  {
    id: 'offline-seed-backup',
    order: 2,
    free: true,
    title: 'Learn offline seed backup concepts',
    summary: 'Understand backups offline. NEVER type seeds into this app.',
    why: 'Self-custody literacy includes knowing that recovery phrases belong offline (paper, metal, or other durable offline methods you research yourself). CustodySteps will never ask for a seed phrase and has no field for one. If a site asks you to paste a seed, treat it as a red flag.',
  },
  {
    id: 'verify-receive-address',
    order: 3,
    free: true,
    title: 'Verify receive addresses on-device',
    summary: 'Compare the address on your wallet screen with what you typed or scanned.',
    why: 'Malware and phishing can swap addresses on a computer screen. Habit: confirm the receive address on the hardware or wallet device itself before sending any meaningful amount. Practice the habit with tiny amounts only when you are ready — this app does not send or receive Bitcoin.',
  },
  {
    id: 'phishing-hygiene',
    order: 4,
    free: true,
    title: 'Recognize phishing patterns',
    summary: 'Bookmark real sites. Ignore urgency and fake support DMs.',
    why: 'Phishing emails, fake “support” chats, and lookalike domains are constant. Bookmark the real URL for exchanges and wallet vendors. Never click “verify your wallet” links from strangers. CustodySteps will never DM you for credentials or seeds.',
  },
  {
    id: 'exchange-2fa',
    order: 5,
    free: true,
    title: 'Turn on 2FA on exchanges before exit',
    summary: 'App-based 2FA (not SMS alone) before you move coins off-exchange.',
    why: 'While funds remain on an exchange, account takeover risk is real. Enable strong two-factor authentication and secure recovery codes offline. This is account security literacy — not investment advice and not a recommendation to buy or sell.',
  },
  {
    id: 'hardware-wallet-research',
    order: 6,
    free: false,
    title: 'Research hardware wallets calmly',
    summary: 'Compare vendors, supply-chain tips, and official docs — no rush.',
    why: 'A hardware wallet is one common path for self-custody, not the only one and not financial advice. Read official documentation, buy from reputable sources, and avoid “too good” third-party sellers. Take notes here on what you researched — never enter device PINs or seeds.',
  },
  {
    id: 'small-test-receive',
    order: 7,
    free: false,
    title: 'Practice a small test receive offline',
    summary: 'When ready, practice receiving a tiny amount and verifying it yourself.',
    why: 'Literacy includes practicing the receive flow with a negligible amount you can afford to lose while learning. Verify the transaction in your own wallet UI. CustodySteps does not connect to wallets, show balances, or call price APIs.',
  },
  {
    id: 'inheritance-awareness',
    order: 8,
    free: false,
    title: 'Inheritance awareness (not legal advice)',
    summary: 'Know that heirs need a plan — this is awareness, not a will or lawyer.',
    why: 'If nobody can access funds after you, literacy is incomplete. Think about who would need instructions and where documentation lives. This is educational awareness only — not estate planning, not legal advice, and not a substitute for a qualified professional.',
  },
  {
    id: 'monthly-review',
    order: 9,
    free: false,
    title: 'Schedule a monthly custody review',
    summary: 'Revisit backups, bookmarks, 2FA, and phishing habits monthly.',
    why: 'Self-custody hygiene drifts. A calm monthly pass over this checklist keeps habits fresh without doomscrolling price charts. Pro users can jot short notes per step to remember what they checked.',
  },
  {
    id: 'social-engineering',
    order: 10,
    free: false,
    title: 'Spot social-engineering red flags',
    summary: 'Urgency, secrecy, remote-control requests, and “send to verify” scams.',
    why: 'Attackers use fear and authority (“your coins will be frozen”) to rush you. Red flags include: demands for seed phrases, remote desktop “help,” secrecy from family, and pressure to act now. Pause. Verify through official channels. Never enter seeds here — there is no input for them by design.',
  },
];

export const FREE_STEP_COUNT = LITERACY_STEPS.filter((s) => s.free).length;
